ARG repository=duguyue100/dgydocker
FROM ${repository}:dl-base-cpu-py3
LABEL maintainer "Yuhuang Hu <duguyue100@gmail.com>"

# Install Xgboost
pip install xgboost

# Install mxnet
pip install mxnet==0.11.0.rc3
